#! /usr/bin/env python
# -.- encoding: utf-8 -.-

import sys
import atexit
import os
import gobject
import signal
import subprocess
import dbus.mainloop.glib
import gettext
import logging

from zeitgeist import config

gettext.install("zeitgeist", config.localedir, unicode=1)
logging.basicConfig(level=logging.DEBUG)

from zeitgeist.engine.engine import get_default_engine
from zeitgeist.engine.remote import RemoteInterface

engine = get_default_engine()

dbus.mainloop.glib.DBusGMainLoop(set_as_default=True)
mainloop = gobject.MainLoop()

obj = RemoteInterface(mainloop = mainloop)

trayicon_app = "%s/zeitgeist-trayicon" % config.bindir
if not "--no-trayicon" in sys.argv and os.path.isfile(trayicon_app):
	subprocess.Popen(trayicon_app)

passive_loggers = "%s/zeitgeist-datahub" % config.bindir
if not "--no-passive-loggers" in sys.argv:
	if os.path.isfile(passive_loggers):
		subprocess.Popen(passive_loggers)
	else:
		logging.warning("%s not found, not starting datahub" % passive_loggers)

obj.EngineStart()
atexit.register(lambda: obj.EngineExit())

logging.info(_("Starting Zeitgeist service..."))
mainloop.run()
