#! /usr/bin/python

import rdflib

def parse(trig_stream):
	trig_in = rdflib.FileInputSource(trig_stream)
	ontology = rdflib.ConjunctiveGraph()
	ontology.parse(trig_in)
	print (len(ontology))
	

if __name__ == "__main__":
	import sys, os
	
	# On no args, read from stdin
	if len(sys.argv) <= 1:
		print >> sys.stderr, "Parsing from stdin"
		parse(sys.stdin)
	else:
		for trig_filename in sys.argv[1:]:
			print >> sys.stderr, "Parsing " + trig_filename
			parse(file(trig_filename))


